blog/urls.py
from django.urls import path
from . import views 


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
] 

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # Blog urls
    path('blog/', include('blog.urls', namespace='blog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager

class PublishedManager(models.Manager): 
    def get_queryset(self): 
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model): 
    STATUS_CHOICES = ( 
        ('draft', 'Draft'),
        ('published', 'Published'), 
    ) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250,  
                            unique_for_date='publish') 
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE,
                               related_name='blog_posts') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft') 
    
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model): 
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

        

blog/views.py
from django.shortcuts import render, get_object_or_404 

from django.contrib.postgres.search import SearchVector
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) 
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag,})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   
                   'comment_form': comment_form,})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='publishsd')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data()
            # Send Email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading" {}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s	comments: {}'.format(post.title, post_url, cd['name'],	cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

    

def post_search(request):

    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data('query')
            results = Post.objects.annotate(search=SearchVector('title', 'body'),).filter(search=query)
            return render(request,
                    'blog/post/search.html',
                    {'form': 'form', 'query': query, 'results':	results})

templates/accounts/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title> 
		<link href="{% static "css/base.css" %}" rel="stylesheet">
	</head>
	<body>  
		<div id="header">
			<span class="logo">Bookmarks</span> 


			  {% if request.user.is_authenticated %}
				<ul class="menu">   
					<li {% if section == "dashboard" %}class="selected"{% endif %}>     
						<a href="{% url "dashboard" %}">My dashboard</a>      </li>      <li {% if section == "images" %}class="selected"{% endif %}>   
						<a href="#">Images</a> 
					</li>   
					<li {% if section == "people" %}class="selected"{% endif %}>    
						<a href="#">People</a>   
					</li>  
				</ul>
				{% endif %} 
				<span class="user"> 
					{% if request.user.is_authenticated %} Hello {{ request.user.first_name }},     
					<a href="{% url "logout" %}">Logout</a>
					{% else %} 
					<a href="{% url "login" %}">Log-in</a> 
					{% endif %}
				</span>
		</div>


		{% if messages %}
		<ul class="messages">
			{% for message in messages %}  
			<li class="{{ message.tags }}">    
				{{ message|safe }}     
				<a href="#" class="close">x</a> 
			</li>   
			{% endfor %} 
		</ul>
		{% endif %}


		<div id="content">
			
			{% block content %}   
			
			
			{% endblock %}  
		</div>
	</body>
</html>

templates/accounts/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<p>Welcome to your dashboard. You can <a href="{% url "edit" %}">edit your profile</a> or <a href="{% url "password_change" %}">change your password</a>.</p>
<p>Welcome to your dashboard.</p>
{% endblock %}

templates/accounts/edit.html
{% extends "base.html" %}

{% block title %}Edit your account{% endblock %}

{% block content %} 
<h1>Edit your account</h1> 
<p>You can edit your account using the following form:</p> 
<form action="." method="post" enctype="multipart/form-data">
	{{ user_form.as_p }}  
	{{ profile_form.as_p }} 
	{% csrf_token %}
	<p><input type="submit" value="Save changes"></p> 
</form>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}{% block content %}  
<h1>Create an account</h1>
<p>Please, sign up using the following form:</p> 
<form action="." method="post"> 
	{{ user_form.as_p }}   
	{% csrf_token %}   
	<p><input type="submit" value="Create my account"></p> 
</form>{% endblock %}

templates/accounts/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1> 
<p>Your account has been successfully created. Now you can <a href="{% url "login" %}">log in</a>.</p>{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">

  <title>{% block head_title %}Juvas Id{% endblock head_title %}</title>

  {% block head_extra %} {% endblock head_extra %}
</head>

<body>


  <!--Main Navigation-->
  <header>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container">
        <!-- Brand --><a class="navbar-brand waves-effect">
		<strong class="blue-text">Juvas</strong>
                </a>
		<!-- Collapse -->
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left -->
          <ul class="navbar-nav mr-auto text-center">
		  <li class="nav-item active"> 
			  <a class="nav-link waves-effect" href="#">Home
				  <span class="sr-only">(current)</span>
			  </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#">About me</a> </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#">Blog</a> </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#">Contact</a>
            </li>
          </ul>

        </div>

      </div>
    </nav>
  </header>




      {% block content %}
      	
      {% endblock content %}


      <!--Footer-->                                                                                         <footer class="page-footer text-center font-small mdb-color darken-2 mt-4 wow fadeIn">

        <!--Call to action-->                                                                                 <div class="pt-4">
            <a class="btn btn-outline-white" href="#" target="_blank" role="button">Hire me
                <i class="fa fa-github ml-2"></i>
            </a>
	</div>
	<hr class="my-4">
        <div class="pb-4">
            <a href="#" target="_blank">
                <i class="fa fa-facebook mr-3"></i>
            </a>
            <a href="#" target="_blank">
                <i class="fa fa-twitter mr-3"></i>
            </a>
	    <a href="" target="_blank">
		    <i class="fa fa-codepen mr-3"></i>
            </a>
        </div>                                                                                                <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2018 Copyright:
            <a href="#" target="_blank">Juvas</a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->


  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>

</body>

</html>

templates/blog/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>

templates/blog/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
	<p class="date">Published {{ post.publish }} by {{ post.author }}</p>{{ post.body|linebreaks }}

	<p>
        <a href="{% url "blog:post_share" post.id %}"> Share this post</a>
      </p>
  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}  
	<li>
		<a href="{{ post.get_absolute_url }}">{{ post.title }}</a> 
	</li>
	{% endfor %}
</ul>

templates/blog/post/list.html
{% extends "base.html" %}


{% load blog_tags %} 


{% block title %}My Blog{% endblock %} 





{% block content %}
<div class="container">

	<div class="row">
		<div class="col">
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "blog/pagination.html" with page=posts %}
		</div>
	</div>
</div>
	
{% endblock content  %}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}